import random
import numpy

def pick3(picks):
    '''
    function takes array of picks for the day and evaluates how they did against autogenerated result
    '''
    #picks= input("put in 3 numbers you pick")
    #picks =['123','234','534']
    inc=0
    result = str(random.randint(0,9))+str(random.randint(0,9))+str(random.randint(0,9))
    counter= [5*[0] for i in range(len(picks))]

    for i in range(len(picks)):
      counter[i][0]=int(picks[i])

    for pick in picks:
      placeholder=str(result)
      count=0
      for n in pick:
        if n in placeholder:
          placeholder= placeholder.replace(n,'',1)
          count+=1
      counter[inc][count+1]+=1
      inc+=1
    #if count<3:
    #    print("you didn't win, you only had ", count, " numbers right. Picked numbers: ", result)
    #else:
    #    print('you won! the picked numbers are ', result)
    return counter, result
